### ISSUE TITLE
Unable to reproduce results as in  original paper

### ISSUE THREAD

**Issue by MayurDivate** [hartonen/PeakXus#1]
I am trying to reproduce results for katainen et. al. data mentioned in the original peakXus paper. 

I have got different results for two analysis compared to results in the original paper. 
note: I am following exactly same parameters as original paper. The difference might be the peakXus version. 

**#commands used in analys**is 

**#Alignment**
bwa aln  ~/Database/Homo_sapiens/UCSC/hg19/Sequence/BWAIndex/genome.fa $input >$out".sai"

bwa samse ~/Database/Homo_sapiens/UCSC/hg19/Sequence/BWAIndex/genome.fa $out".sai" $input >$out".sam"

samtools view -@ 3 -bS -o $out".bam"  $out".sam"

**#Moods**

~/Tools/MOODS-python-1.9.3/scripts/moods_dna.py -S CTCF.pfm -s 
~/Database/Homo_sapiens/UCSC/hg19/Sequence/WholeGenomeFasta/genome.fa -p 0.0001

Top 300000 peaks were selected for downstream analysis. 
 
**#Peakxus:**

python ~/Tools/PeakXus-master/src/PeakXus.py $inputbam $out"_PeakXus_out"/ ../genome.chrom.szies --wg7 ~/Database/Homo_sapiens/UCSC/hg19/Sequence/WholeGenomeFasta/genome.fa

**Issue 1:**   overlapping HARS sites vs the number of best peaks analyzed plot. 
I got just 1500 HARS sites overlapped whereas original paper shows 30000 overlapping HARS sites with 4X10^5 best peaks.  

original paper plot 
![screen shot 2017-08-28 at 11 41 42 am](https://user-images.githubusercontent.com/10526942/29758483-7c2b52fa-8be6-11e7-838d-0f92ada81790.png)

my result plot  

![screen shot 2017-08-28 at 11 42 10 am](https://user-images.githubusercontent.com/10526942/29758515-b85c4888-8be6-11e7-90bf-2143734c8be9.png)

**Issue 2:** average 5' end read count around peak summit is different compared to original paper 

original paper distribution 
![screen shot 2017-08-28 at 11 51 57 am](https://user-images.githubusercontent.com/10526942/29758801-f2dc9af6-8be8-11e7-96ec-1b0c5443e589.png)

my result 
![screen shot 2017-08-28 at 12 02 46 pm](https://user-images.githubusercontent.com/10526942/29758804-fcc36ebe-8be8-11e7-942b-7c3aa975731a.png)

What do you think, what can be the possible reasons?

Thank you,
Mayur

**Comment by hartonen** [comment]
Hi Mayur!

Thanks for a detailed report, here are my thoughts:

Issue 1)

I think the issue here is that our lists of the top 300k HARS-sites are different. I downloaded the Katainen et. al CTCF experiment and run the analysis again from scratch and got a result very similar to the one shown in our paper (with the newest version of PeakXus), see figure below

![motifsperpeak_m 20o 1](https://user-images.githubusercontent.com/16348930/29774719-3b52e23c-8c0b-11e7-85e2-8a633bf1bd4f.png)

Moreover, the total number of peaks called by PeakXus seems almost the same between your result and ours (judging from the figure). To me this would imply that the difference is in the locations of the HARS-sites. Can you maybe send me the pfm-file for the CTCF motif and I can try to replicate your result? The HARS-file we used in our paper was generated with an older version of MOODS which can also play a role here (which is of course not nice if this is the case).

Maybe you could also send me the log.txt and all_transition_points.igv files from your output so that I can take a look and see if anything looks out of place? Which chromosomes you use in your run? We used 1-22 and X.

Issue 2)

The figure from our paper that you linked shows the _method specific_ peaks for PeakXus. This means that it only shows the peaks that PeakXus reports these but Peakzilla and MACE do not. On the other hand, the figure you linked from your PeakXus run output shows just the top 1000 peaks ranked by PeakXus score. So basically these figures are not comparable. The figure from your PeakXus output looks OK to me.

Best,
Tuomo

**Comment by MayurDivate** [comment]
Hi Tumoto,

I am really thankful to you for your prompt response.

## issue 1 :

We used **CTCF motif pfm f**rom following file  
[1-s2.0-S009286741201496-mmc3.xlsx](https://github.com/hartonen/PeakXus/files/1259067/1-s2.0-S009286741201496-mmc3.xlsx)
----------

**the log.txt file :**

[log.txt](https://github.com/hartonen/PeakXus/files/1259094/log.txt)
----------

**the igv file:** 

[all_transition_points.igv.zip](https://github.com/hartonen/PeakXus/files/1259096/all_transition_points.igv.zip)
----------

## We are using all chromosome in our run. 

## HOW TO USE REPLICATES RUN PeakXus?
Are you merging replicates before using PeakXus or after peakXus ?
If it is after PeakXus then could you please tell me the strategy for merging replicates ? 
 
## issue 2: thank you for explanation, it is really useful.    

Thank you,
Mayur

**Comment by hartonen** [comment]
Hi Mayur,

The issue is indeed in the list of HARS-sites. The CTCF motif you use is indeed in pfm (position frequency matrix) format, but when you call MOODS you set the input flag '-S' which causes the program to expect that the matrix is already in pwm (position weight matrix) format. When I ran MOODS with the pfm-file you linked as an input using the '-m' input flag instead of '-S', I got the same result as in our paper and in the figure I attached to my previous post. Wikipedia has a nice article about the pwm if you are not familiar with them: https://en.wikipedia.org/wiki/Position_weight_matrix

Otherwise I get the same peak calling output as you and everything seems to be OK!

Just as a suggestion, we are nowadays filtering the ENCODE blacklisted regions (https://sites.google.com/site/anshulkundaje/projects/blacklists) out of the peak calls as we have observed that for example centromere regions usually always contain artefact peaks that can sometimes get a relatively high score as there is no control sample available in ChIP-exo/nexus. I strongly advice to use the ENCODE blacklisted regions in any analysis with PeakXus, blacklisted regions can be given as input for PeakXus in BED format using the '--blacklist' handle.

In my opinion it makes more sense to call peaks separately for both of the replicates.  This way you should get the sets of peaks for both of your biological replicates, after which you can decide how to determine which peaks are consistently reproduced. One option might be to use IDR (https://sites.google.com/site/anshulkundaje/projects/idr) as a metric, but I have not really studied in that much detail what would be the best way to handle replicates for ChIP-exo/nexus.

Anyway, I hope this helps, and to me it seems that the issue is solved if you change the input flag for MOODS as I suggested above.

Best,
Tuomo

**Comment by MayurDivate** [comment]
Hi Sudhir,

FYI

Mayur


Mayur Divate
Research Assistant (Bioinformatics)
*Faculty of Health Sciences,*
*University of Macau,*
Avenida da Universidade,
Taipa, Macau, SAR China
Mobile: +91 80 87 127314  or + 853 6299 1370

[image: Twitter] <https://twitter.com/Mayur_Divate>  [image: Facebook]
<http://facebook.com/mayurdivate>  [image: LinkedIn]
<http://in.linkedin.com/pub/mayur-divate/55/305/366>  [image: GooglePlus]
<https://plus.google.com/+MayurDivate/>
*Confidentiality Note: *If you received this email in error please delete
and notify sender.

**Comment by MayurDivate** [comment]
Thank you so much, Tuomo !!

That was very helpful, Now can replicate the results.

Thanks again,
Mayur
